---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/bookmarks

- Développement:
    - Github:
        - icon: /images/github.png
          href: https://github.com/

- Social:
    - Discord:
        - icon: /images/discord.png
          href: https://discord.com/

- Divertissement:
    - YouTube:
        - icon: /images/youtube.png
          href: https://youtube.com/
    - Steam:
        - icon: /images/steam.png
          href: https://steam.com/
