---
- name: Ensure systemd-resolved is started and enabled
  ansible.builtin.systemd:
    name: systemd-resolved
    state: started
    enabled: true

- name: Update apt cache
  become: true
  ansible.builtin.apt:
    update_cache: true
    upgrade: dist
    cache_valid_time: 3600

- name: Install Dependencies
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - curl
    - net-tools
    - nginx

- name: Mount NAS
  ansible.posix.mount:
    src: /dev/sdb
    path: /media
    fstype: ntfs
    opts: ro,auto
    state: mounted
