---
- name: Ensure systemd-resolved is started and enabled
  ansible.builtin.systemd:
    name: systemd-resolved
    state: started
    enabled: true

- name: Update apt cache
  become: true
  ansible.builtin.apt:
    update_cache: true
    upgrade: dist
    cache_valid_time: 3600

- name: Install Dependencies
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - curl
    - net-tools

- name: Send utils directory
  ansible.builtin.copy:
    dest: /home/{{ ansible_user }}/
    src: ./utils/
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'

- name: Change autorun permissions
  ansible.builtin.file:
    path: /home/{{ ansible_user }}/autorun.sh
    mode: '0755'

- name: Add hostname in local.conf
  ansible.builtin.replace:
    path: /home/{{ ansible_user }}/nginx/local.conf
    regexp: 'HOST_ANSIBLE'
    replace: '{{ ansible_host }}'

- name: Add hostname in compose.yml
  ansible.builtin.replace:
    path: /home/{{ ansible_user }}/compose.yml
    regexp: 'HOST_ANSIBLE'
    replace: '{{ ansible_host }}'

- name: Create cert directory
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/cert/"
    state: directory
    mode: '0755'

- name: Generate a Self Signed OpenSSL certificate
  openssl_certificate:
    path: "/home/{{ ansible_user }}/cert/cert.pem"
    privatekey_path: "/home/{{ ansible_user }}/cert/key.pem"
    provider: selfsigned
