---
- name: Install certbot
  community.general.snap:
    name: certbot
    classic: true

- name: Prepare the Certbot command
  ansible.builtin.file:
    src: /snap/bin/certbot
    dest: /usr/bin/certbot
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: link
  notify:
    - Get a certbot certificate

- name: Launch all handlers
  ansible.builtin.meta: flush_handlers
