services:
  jellyfin:
    image: jellyfin/jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - JELLYFIN_PublishedServerUrl=http://HOST_ANSIBLE/jellyfin
    volumes:
      - /srv/Jellyfin/config:/config
      - /srv/Jellyfin/cache:/cache
      - /srv/Jellyfin/data:/data
      - /srv/Jellyfin/media:/media
      - /srv/Jellyfin/media2:/media2:ro
    ports:
      - 8096:8096
    restart: unless-stopped
    networks:
      - jellyfin-network

  netdata:
    image: netdata/netdata
    container_name: netdata
    pid: host
    restart: unless-stopped
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
    # ports:
    #   - 19999:19999
    volumes:
      - netdataconfig:/etc/netdata
      - netdatalib:/var/lib/netdata
      - netdatacache:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /etc/localtime:/etc/localtime:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
      - /var/log:/host/var/log:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - jellyfin-network
      - vault-network
      - filebrowser-network

  vault:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      DOMAIN: "https://HOST_ANSIBLE/vault/"
      SIGNUPS_ALLOWED: "true"
    volumes:
      - /srv/vw-data/:/data/
    # ports:
    #   - 8080:80
    networks:
      - vault-network

  filebrowser:
    image: filebrowser/filebrowser:s6
    container_name: filebrowser
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /srv/filebrowser/srv:/srv
      - /srv/filebrowser/database:/database
      - /srv/filebrowser/config:/config
    # ports:
    #   - 8080:80
    restart: unless-stopped
    networks:
      - filebrowser-network

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    environment:
      PUID: 1000 # optional, your user id
      PGID: 1000 # optional, your group id
    volumes:
      - /srv/current/homepage/config:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock:ro # optional, for docker int>
      - /srv/current/homepage/images:/app/public/images
    restart: unless-stopped
    scale: 5
    # ports:
    #   - 3000:3000
    networks:
      - homepage-network

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - /srv/current/nginx/local.conf:/etc/nginx/nginx.conf:ro
      - /srv/cert/:/etc/nginx/ssl/:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    restart: unless-stopped
    depends_on:
      jellyfin:
        condition: service_started
      netdata:
        condition: service_started
      vault:
        condition: service_started
      filebrowser:
        condition: service_started
      homepage:
        condition: service_started
    ports:
      - 80:80
      - 443:443
    networks:
      - jellyfin-network
      - vault-network
      - filebrowser-network
      - homepage-network

volumes:
  netdataconfig:
  netdatalib:
  netdatacache:
networks:
  jellyfin-network:
  vault-network:
  filebrowser-network:
  homepage-network:
